### PR TITLE
Python 3 compatibility

### LINKED ISSUE #62: python 3 compatibility
I believe that OM10 is still required by Twinkles.  For DESC, we've decided that all production code will be run under python 3.  This repo needs some updates to be py3 compatible.

### PR DESCRIPTION
**Pull request by drphilmarshall**
I'm using this PR to have travis test python 3.5 as well as 2.7. Closes #62 when  merged.

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Hmm. I'm not sure why travis is failing - something wrong with the way it is being setup? @jchiang87 do you mind checking out the `issue/62/py3` branch and running `nosetests` please? You'll need to do a `python setup.py develop` in the om10 dir first.

**Comment by drphilmarshall** [comment]
PS. I think I made om10 correctly python 2 and 3 compatible.

**Comment by jchiang87** [comment]
@drphilmarshall I'm having problems setting up this package on my laptop.  Where can I get the `indexTricks` package?  Also, I think LensPop will need a python3 compatibility sweep.

**Comment by drphilmarshall** [comment]
Issued python 3 compatibility work in my fork of LensPop at https://github.com/drphilmarshall/LensPop/issues/3 

BTW `indexTricks.py` is a module in the top level of my fork of LensPop - so that's a packaging issue that needs fixing...

**Comment by drphilmarshall** [comment]
OK, @jbkalmbach fixed the python 3 compatibility in OM10 and in `lenspop`, so we should be good - though it'd be nice to see travis pass...

**Comment by drphilmarshall** [comment]
... close, but py 3.5 fails (an `import distance` error in `lenspop`): here's the [travis log](https://travis-ci.org/drphilmarshall/OM10/jobs/334959650)

**Comment by drphilmarshall** [comment]
@jbkalmbach you've cracked it: [travis now passes](https://travis-ci.org/drphilmarshall/OM10/builds/334959653). Merging - and thank you for making this work! :-)

**Pull request merged**
