### PR TITLE
Issue/02/weight

### PR DESCRIPTION
**Pull request by jennykim1016**

### CODE REVIEW

**Comment by drphilmarshall** [comment]
Looks like you need to `git pull base master` into this branch and fix the conflict in `om10/db.py` before checking in again!

**Comment by jennykim1016** [comment]
Oops, sorry; I did not intend to merge to your directory; I wanted to merge first with my master directory from the branch. I will merge into your directory after checking everything once again!

**Comment by drphilmarshall** [comment]
Also, the notebooks folder seems to have a lot of additional stuff in it (untitled notebooks, data files, pickles etc) that need cleaning out. We should try to keep the checked in notebooks to a minimum - with the code painting both the lenses and quasars at the same time, I was hoping we'd just need one "painting demo" notebook. Is it possible?

**Comment by drphilmarshall** [comment]
Ah, OK! See my comment about notebook consolidation though, in case you haven't done this already. Thanks, Jenny!

**Pull request closed without merging**
